---
title: "R Notebook"
output: html_notebook
---


```{r}
library(data.table)
library(tidyverse)
library(sampleSelection)
library(SemiParSampleSel)
library(haven)
library(lmtest)
library(sandwich)
```

### women wages

```{r}
women <- read_stata("../data-raw/womenwk.dta") 
women$selection <- !is.na(women$wage)
summary(women)
```


```{r}
m0 <- glm(wage ~  education + age, 
             data = women,
           subset = selection)
summary(m0)
```

```{r}
m1 <- heckit(selection ~ married + children+ education +age,
             wage ~  education + age, 
             data = women)
summary(m1)
```

```{r}
m2 <- heckit(selection ~ married + children+ education +age,
             wage ~  education + age, 
             data = women,
             method = "ml")
summary(m2)
```

```{r}
m3 <- SemiParSampleSel(
  formula = list(selection ~ married + children+ education +age,
             wage ~  education + age),
  data = women,
  margin = c("probit", "N")
)
summary(m3)
```

We can also account for the correlation within county using `lmtest` and `sandwich` estimator.

```{r}
coeftest(m2, vcov = vcovCL(m2, cluster = women$county))
```



