---
title: "R Notebook"
output: html_notebook
---

# Create contingency tables

## R

Packages

```{r}
library(vcdExtra)
library(gmodels)
```

Read in the dataset about units that were sampled 

```{r}
df <- readRDS("../data-raw/data_for_lecture.rds")
```

```{r}
glimpse(df)
```

### create contingency table


```{r}
CrossTable(df$gender,df$status)
```

```{r}
xtabs(~gender+status, df)
```

### odds, log odds, odds ratio and log odds ratio

```{r}
status_gender <- xtabs(~gender+status, df)

odds(status_gender, log = F)
odds(status_gender, log = T)
oddsratio(status_gender, log = F)
oddsratio(status_gender, log = T)
```

```{r}
summary(status_gender)
```

```{r}
fisher.test(status_gender)
```


## Python

```{python, engine.path = "~/anaconda3/bin/python"}
import pandas as pd
import statsmodels.api as sm

df = pd.read_csv("../data-raw/data_for_lecture.txt")
table = sm.stats.Table2x2.from_data(df[["gender", "status"]])
print(table.test_nominal_association()) ## test chi2
print(table.summary()) ## ods ratios and more
```

## Julia

```{r}

```

# Correlations

# Contingency table


